/**
 * RiceBaCI-GEE — Module 07: Active-learning review app
 * ---------------------------------------------------------------------------
 * Author:   Supranab Panda  (pandasupranab@gmail.com)
 * Project:  RiceBaCI-GEE   OSF c4mp8
 * Purpose:  Review the ~480 candidate label points generated by Module 06.
 *           For each candidate, the map auto-zooms in and a side panel shows
 *           pixel diagnostics. User clicks Keep / Reject / Skip.
 *           Decisions accumulate in a local dictionary, then export to Drive
 *           as a single CSV when finished.
 *
 * How to use
 * ---------------------------------------------------------------------------
 *  1. Confirm Module 06 export task 'candidates_v3_export' has finished
 *     (Assets tab -> projects/durable-pulsar-486209-b5/assets/candidates_v3
 *      should exist).
 *  2. Paste this entire file into a new Code Editor script named
 *     '07_active_learning_review'.  Save.
 *  3. Click Run. The first candidate appears in the map. Click Keep / Reject
 *     / Skip in the right-side panel. Repeat ~480 times (about 25 min).
 *  4. When done, click EXPORT DECISIONS button (bottom of panel). A task
 *     'review_decisions_export' appears in the Tasks tab.
 *  5. Run the task. CSV lands in Drive at /RiceBaCI_labels/review_decisions.csv.
 *  6. Reply to the agent with the CSV attached.
 * ---------------------------------------------------------------------------
 */

var CLOUD_PROJECT = 'projects/durable-pulsar-486209-b5/assets';
var CANDIDATES = ee.FeatureCollection(CLOUD_PROJECT + '/candidates_v3');

// ---------------------------------------------------------------------------
// State (lives in the Code Editor session)
// ---------------------------------------------------------------------------
var state = {
  candidates: null,    // client-side array
  idx: 0,
  decisions: {}         // { candidate_id: 'keep' | 'reject' | 'skip' }
};

// ---------------------------------------------------------------------------
// UI Panel
// ---------------------------------------------------------------------------
var panel = ui.Panel({style: {width: '380px', padding: '10px'}});
panel.add(ui.Label('RiceBaCI active-learning review',
  {fontWeight: 'bold', fontSize: '18px', color: '#01696F'}));
panel.add(ui.Label('Module 07', {fontSize: '12px', color: '#7A7974'}));

var progressLbl = ui.Label('Loading candidates...');
panel.add(progressLbl);

var infoPanel = ui.Panel({style: {margin: '8px 0', padding: '8px',
  backgroundColor: '#F9F8F5', border: '1px solid #D4D1CA'}});
panel.add(infoPanel);

var keepBtn   = ui.Button({label: '✓ KEEP (k)',     style: {color: '#437A22', stretch: 'horizontal'}});
var rejectBtn = ui.Button({label: '✗ REJECT (r)',   style: {color: '#A13544', stretch: 'horizontal'}});
var skipBtn   = ui.Button({label: '◦ SKIP (s)',     style: {color: '#7A7974', stretch: 'horizontal'}});
var prevBtn   = ui.Button({label: '< Previous',     style: {stretch: 'horizontal'}});
var nextBtn   = ui.Button({label: 'Next without decision >', style: {stretch: 'horizontal'}});

panel.add(keepBtn);
panel.add(rejectBtn);
panel.add(skipBtn);
panel.add(ui.Panel([prevBtn, nextBtn], ui.Panel.Layout.flow('horizontal')));

var summaryLbl = ui.Label('', {margin: '8px 0', fontSize: '12px'});
panel.add(summaryLbl);

var exportBtn = ui.Button({
  label: 'EXPORT DECISIONS to Drive',
  style: {backgroundColor: '#01696F', color: '#FFFFFF', stretch: 'horizontal', margin: '12px 0'}
});
panel.add(exportBtn);

ui.root.insert(0, panel);

// ---------------------------------------------------------------------------
// Load candidates client-side
// ---------------------------------------------------------------------------
CANDIDATES.toList(1000).evaluate(function (lst) {
  if (!lst || lst.length === 0) {
    progressLbl.setValue('No candidates loaded. Did Module 06 export finish?');
    return;
  }
  state.candidates = lst;
  // initialise all decisions as pending
  lst.forEach(function (f) {
    state.decisions[f.properties.candidate_id] = 'pending';
  });
  showCandidate(0);
});

// ---------------------------------------------------------------------------
// Show one candidate
// ---------------------------------------------------------------------------
function showCandidate(i) {
  if (!state.candidates) return;
  i = Math.max(0, Math.min(state.candidates.length - 1, i));
  state.idx = i;
  var feat = state.candidates[i];
  var p = feat.properties;
  var coords = feat.geometry.coordinates;
  var lon = coords[0], lat = coords[1];
  var pt = ee.Geometry.Point([lon, lat]);

  progressLbl.setValue('Candidate ' + (i + 1) + ' / ' + state.candidates.length +
    '   (id ' + p.candidate_id + ')');

  // Refresh info panel
  infoPanel.clear();
  var color = (p.class_proposed === 'cyclone_flood') ? '#A12C7B' : '#DA7101';
  infoPanel.add(ui.Label('Class proposed: ' + p.class_proposed,
    {fontWeight: 'bold', color: color, fontSize: '14px'}));
  infoPanel.add(ui.Label('Cyclone/event: ' + (p.cyclone || 'none') +
    '   year: ' + (p.year || '-')));
  if (p.district) infoPanel.add(ui.Label('District: ' + p.district));
  infoPanel.add(ui.Label('lon, lat: ' + lon.toFixed(4) + ', ' + lat.toFixed(4)));
  infoPanel.add(ui.Label('SI:   ' + (p.si   !== null ? Number(p.si).toFixed(3)   : '?')));
  infoPanel.add(ui.Label('NDWI: ' + (p.ndwi !== null ? Number(p.ndwi).toFixed(3) : '?')));
  infoPanel.add(ui.Label('NDVI: ' + (p.ndvi !== null ? Number(p.ndvi).toFixed(3) : '?')));
  infoPanel.add(ui.Label('VH:   ' + (p.vh   !== null ? Number(p.vh).toFixed(2) + ' dB' : '?')));
  infoPanel.add(ui.Label('Window: ' + (p.window_start || p.source_date || '-') +
    ' → ' + (p.window_end || '-')));
  infoPanel.add(ui.Label('Current decision: ' + state.decisions[p.candidate_id],
    {fontStyle: 'italic'}));

  // Load imagery for the right date window
  var startDate, endDate;
  if (p.class_proposed === 'cyclone_flood') {
    startDate = ee.Date(p.window_start);
    endDate   = ee.Date(p.window_end);
  } else {
    startDate = ee.Date.fromYMD(p.year, 7, 1);
    endDate   = ee.Date.fromYMD(p.year, 8, 31);
  }
  var s2col = ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
    .filterBounds(pt.buffer(2000))
    .filterDate(startDate, endDate)
    .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 60));
  var s2 = s2col.median().divide(10000);
  var s1 = ee.ImageCollection('COPERNICUS/S1_GRD')
    .filterBounds(pt.buffer(2000))
    .filterDate(startDate, endDate)
    .filter(ee.Filter.eq('instrumentMode', 'IW'))
    .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH'))
    .select('VH').median();

  Map.layers().reset();
  Map.addLayer(s2.select(['B4','B3','B2']),
    {min: 0, max: 0.30, gamma: 1.3}, 'S2 RGB', true);
  Map.addLayer(s2.select(['B11','B8','B4']),
    {min: 0, max: 0.45, gamma: 1.2}, 'S2 false-colour', false);
  Map.addLayer(s2.normalizedDifference(['B3','B8']),
    {min: -0.3, max: 0.6, palette: ['440154','3b528b','21918c','5ec962','fde725']},
    'NDWI', false);
  Map.addLayer(s1, {min: -25, max: -5, palette: ['000000','555555','ffffff']},
    'S1 VH (dB)', false);
  Map.addLayer(pt.buffer(50), {color: color}, 'Candidate', true);
  Map.centerObject(pt, 16);

  updateSummary();
}

// ---------------------------------------------------------------------------
// Decision handlers
// ---------------------------------------------------------------------------
function decide(verdict) {
  if (!state.candidates) return;
  var feat = state.candidates[state.idx];
  state.decisions[feat.properties.candidate_id] = verdict;
  // Auto-advance
  if (state.idx < state.candidates.length - 1) {
    showCandidate(state.idx + 1);
  } else {
    progressLbl.setValue('All ' + state.candidates.length + ' candidates reviewed.');
    updateSummary();
  }
}

keepBtn.onClick(function () { decide('keep'); });
rejectBtn.onClick(function () { decide('reject'); });
skipBtn.onClick(function () { decide('skip'); });
nextBtn.onClick(function () { if (state.candidates) showCandidate(state.idx + 1); });
prevBtn.onClick(function () { if (state.candidates) showCandidate(state.idx - 1); });

// ---------------------------------------------------------------------------
// Summary counter
// ---------------------------------------------------------------------------
function updateSummary() {
  var k = 0, r = 0, s = 0, p = 0;
  Object.keys(state.decisions).forEach(function (id) {
    var d = state.decisions[id];
    if (d === 'keep') k++;
    else if (d === 'reject') r++;
    else if (d === 'skip') s++;
    else p++;
  });
  summaryLbl.setValue(
    'Decisions so far → keep: ' + k + '   reject: ' + r + '   skip: ' + s + '   pending: ' + p
  );
}

// ---------------------------------------------------------------------------
// Export decisions to Drive
// ---------------------------------------------------------------------------
exportBtn.onClick(function () {
  if (!state.candidates) return;
  var rows = state.candidates.map(function (feat) {
    var p = feat.properties;
    var d = state.decisions[p.candidate_id];
    return ee.Feature(null, {
      candidate_id: p.candidate_id,
      class_proposed: p.class_proposed,
      class_id: p.class_id,
      cyclone: p.cyclone,
      year: p.year,
      district: p.district || null,
      lon: p.lon,
      lat: p.lat,
      si: p.si,
      ndwi: p.ndwi,
      ndvi: p.ndvi,
      vh: p.vh,
      window_start: p.window_start || null,
      window_end: p.window_end || null,
      decision: d,
      reviewer: 'pandasupranab',
      reviewed_on: new Date().toISOString().slice(0,10)
    });
  });
  var fc = ee.FeatureCollection(rows);
  Export.table.toDrive({
    collection: fc,
    description: 'review_decisions_export',
    folder: 'RiceBaCI_labels',
    fileNamePrefix: 'review_decisions_' + new Date().toISOString().slice(0,10),
    fileFormat: 'CSV'
  });
  progressLbl.setValue('Export task dispatched. Open Tasks tab → Run.');
});

print('Module 07 review app loaded. Use the panel on the right.');
